import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		environment: "node",
		include: ["tests/**/*.test.ts"],
		globalSetup: ["./tests/global-setup.ts"],
		// Deterministic test environment: silent logs, fast bcrypt, and JWT
		// keys generated by the global setup instead of real secrets.
		env: {
			NODE_ENV: "test",
			LOG_LEVEL: "silent",
			BCRYPT_SALT_ROUNDS: "4",
			JWT_PASSPHRASE: "test-passphrase",
			JWT_PRIVATE_KEY_PATH: "tests/.tmp/keys/private.pem",
			JWT_PUBLIC_KEY_PATH: "tests/.tmp/keys/public.pem",
		},
	},
});
